name: test action

on:
  workflow_dispatch:
  push:

jobs:
  # set-env:
  #   runs-on: ubuntu-22.04
  #   outputs:
  #     refs: ${{ steps.refs.outputs.value }}
  #   steps:
  #     - id: refs
  #       run: echo "value=develop" >> $GITHUB_OUTPUT
  test:
    name: test-action
    runs-on: ubuntu-22.04
    # needs: [set-env]
    steps:
      - uses: actions/checkout@v3
      # needsコンテキストでバージョンは変えられない
      # - uses: kazuo278/composite-action@${{ needs.set-env.outputs.refs }}
      #   with:
      #     java_version: 11-jdk
      #     test_str: Hello Java with Composite Action
      - uses: actions/checkout@v3
        with:
          repository: aquasecurity/trivy-action
          path: trivy
      - name: クローン確認
        run: |
          ls -la trivy
      - name: Dockerfile 書き換え
        run: |
          # versionのか書き換え
          sed -i "s/0.34.0/0.36.0/g" trivy/Dockerfile
          # 書き換えの確認のためentrypoint.shを書き換え
          cat << EOS > trivy/entrypoint.sh
          #!/bin/bash
          trivy version
          echo
          EOS
      - uses: ./trivy/
        with:
          # 必須引数なのでとりあえず指定
          image-ref: centos:7
